name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7
  video_player: ^2.5.1
  chewie: ^1.2.3 # Video Player Wrapper to control video playback
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  go_router: ^13.2.1
  rxdart: ^0.27.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
